win32:LIBS += -lDbgHelp -luser32

# 支持release模式下，行号等信息导出
DEFINES += QT_MESSAGELOGCONTEXT
QMAKE_CXXFLAGS_RELEASE = $$QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO
QMAKE_LFLAGS_RELEASE = $$QMAKE_LFLAGS_RELEASE_WITH_DEBUGINFO

INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD

HEADERS += \
    $$PWD/qtlog.h

SOURCES += \
    $$PWD/qtlog.cpp

#CONFIG +=console

